### ISSUE TITLE
Python 3.x compatibility

### ISSUE THREAD

**Issue by nicoborghi** [crpurcell/friendlyVRI#6]
In order to execute the code with Python 3.x those steps are needed:

- **vriTk.py**: replace `NavigationToolbar2TkAgg` with `NavigationToolbar2Tk` and `self.figCanvas.show()` with `self.figCanvas.draw()`

- **Imports/util_tk.py**: replace `NavigationToolbar2TkAgg` with `NavigationToolbar2Tk`

**Comment by masolimano** [comment]
Hi @nicoborghi, did it work for you? You can see my PR #5 which applies exactly those changes but it fails to display properly anyway

**Comment by crpurcell** [comment]
Latest version now working and tested in Anaconda Python 3.9.
